# Generated by Django 4.0.8 on 2022-11-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=100)),
                ('ticker_time', models.DateTimeField()),
                ('ticker_price', models.IntegerField()),
            ],
            options={
                'get_latest_by': ['ticker_name', 'ticker_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.UniqueConstraint(fields=('ticker_name', 'ticker_time'), name='unique_ticker_time_combination'),
        ),
    ]
