# Generated by Django 4.0.8 on 2022-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'get_latest_by': ['name', 'time']},
        ),
        migrations.RemoveConstraint(
            model_name='ticker',
            name='unique_ticker_time_combination',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker_time',
            new_name='time',
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.UniqueConstraint(fields=('name', 'time'), name='unique_name_time_combination'),
        ),
    ]
