# Generated by Django 4.0.8 on 2022-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_ticker_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'get_latest_by': ['time', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='ticker',
            name='unique_name_time_combination',
        ),
        migrations.AddConstraint(
            model_name='ticker',
            constraint=models.UniqueConstraint(fields=('time', 'name'), name='unique_time_name_combination'),
        ),
    ]
